// <auto-generated />
using System;
using EPassport.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EPassport.Migrations
{
    [DbContext(typeof(EPassportContext))]
    [Migration("20220508125402_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EPassport.Models.AddressDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicantID");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("District")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EmailID");

                    b.Property<string>("HouseNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Pincode")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreetName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelephoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.ToTable("AddressDetails");
                });

            modelBuilder.Entity("EPassport.Models.ApplicationDetail", b =>
                {
                    b.Property<int>("ApplicantId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicantID");

                    b.Property<string>("District")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("EducationalQualification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoginId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoginID");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PAN");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ApplicantId");

                    b.HasIndex("LoginId");

                    b.ToTable("ApplicationDetails");
                });

            modelBuilder.Entity("EPassport.Models.AppointmentDetail", b =>
                {
                    b.Property<int>("MonthId")
                        .HasColumnType("int")
                        .HasColumnName("MonthID");

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicantID");

                    b.Property<string>("AvailableDays")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MonthName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TimeSlots")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MonthId");

                    b.HasIndex("ApplicantId");

                    b.ToTable("AppointmentDetails");
                });

            modelBuilder.Entity("EPassport.Models.FamilyDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicantID");

                    b.Property<string>("FathersName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MothersName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.ToTable("FamilyDetails");
                });

            modelBuilder.Entity("EPassport.Models.LoginCredential", b =>
                {
                    b.Property<string>("LoginId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoginID");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("LoginId");

                    b.ToTable("LoginCredentials");
                });

            modelBuilder.Entity("EPassport.Models.PassportOffice", b =>
                {
                    b.Property<int>("OfficeId")
                        .HasColumnType("int")
                        .HasColumnName("OfficeID");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicantID");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OfficeId");

                    b.HasIndex("ApplicantId");

                    b.ToTable("PassportOffice", (string)null);
                });

            modelBuilder.Entity("EPassport.Models.ReferenceDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicantID");

                    b.Property<string>("ReferenceName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelephoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.ToTable("ReferenceDetails");
                });

            modelBuilder.Entity("EPassport.Models.RegistrationDetail", b =>
                {
                    b.Property<string>("LoginId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoginID");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("DOB");

                    b.Property<string>("EmailId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EmailID");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LoginId");

                    b.ToTable("RegistrationDetails");
                });

            modelBuilder.Entity("EPassport.Models.SupportingDocumentDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicantID");

                    b.Property<byte[]>("Document1")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Document2")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.ToTable("SupportingDocumentDetails");
                });

            modelBuilder.Entity("EPassport.Models.AddressDetail", b =>
                {
                    b.HasOne("EPassport.Models.ApplicationDetail", "Applicant")
                        .WithMany("AddressDetails")
                        .HasForeignKey("ApplicantId")
                        .HasConstraintName("FK_AddressDetails_ApplicationDetails");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("EPassport.Models.ApplicationDetail", b =>
                {
                    b.HasOne("EPassport.Models.RegistrationDetail", "Login")
                        .WithMany("ApplicationDetails")
                        .HasForeignKey("LoginId")
                        .HasConstraintName("FK_ApplicationDetails_RegistrationDetails");

                    b.Navigation("Login");
                });

            modelBuilder.Entity("EPassport.Models.AppointmentDetail", b =>
                {
                    b.HasOne("EPassport.Models.ApplicationDetail", "Applicant")
                        .WithMany("AppointmentDetails")
                        .HasForeignKey("ApplicantId")
                        .HasConstraintName("FK_AppointmentDetails_ApplicationDetails");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("EPassport.Models.FamilyDetail", b =>
                {
                    b.HasOne("EPassport.Models.ApplicationDetail", "Applicant")
                        .WithMany("FamilyDetails")
                        .HasForeignKey("ApplicantId")
                        .HasConstraintName("FK_FamilyDetails_ApplicationDetails");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("EPassport.Models.LoginCredential", b =>
                {
                    b.HasOne("EPassport.Models.RegistrationDetail", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId")
                        .HasConstraintName("FK_LoginCredentials_RegistrationDetails");

                    b.Navigation("Login");
                });

            modelBuilder.Entity("EPassport.Models.PassportOffice", b =>
                {
                    b.HasOne("EPassport.Models.ApplicationDetail", "Applicant")
                        .WithMany("PassportOffices")
                        .HasForeignKey("ApplicantId")
                        .HasConstraintName("FK_PassportOffice_ApplicationDetails");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("EPassport.Models.ReferenceDetail", b =>
                {
                    b.HasOne("EPassport.Models.ApplicationDetail", "Applicant")
                        .WithMany("ReferenceDetails")
                        .HasForeignKey("ApplicantId")
                        .HasConstraintName("FK_ReferenceDetails_ApplicationDetails");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("EPassport.Models.SupportingDocumentDetail", b =>
                {
                    b.HasOne("EPassport.Models.ApplicationDetail", "Applicant")
                        .WithMany("SupportingDocumentDetails")
                        .HasForeignKey("ApplicantId")
                        .HasConstraintName("FK_SupportingDocumentDetails_ApplicationDetails");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("EPassport.Models.ApplicationDetail", b =>
                {
                    b.Navigation("AddressDetails");

                    b.Navigation("AppointmentDetails");

                    b.Navigation("FamilyDetails");

                    b.Navigation("PassportOffices");

                    b.Navigation("ReferenceDetails");

                    b.Navigation("SupportingDocumentDetails");
                });

            modelBuilder.Entity("EPassport.Models.RegistrationDetail", b =>
                {
                    b.Navigation("ApplicationDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
